# Database credentials
database:
  # antingen denna
  file: "database/sqlite" 
  # eller alla dessa (om file är blankt)
  sql-user: ""            #
  sql-pass: ""
  sql-server: "127.0.0.1"
  sql-database: "Whiteboard"
  sql-port: 3306

whiteboard:
  width: 100
  height: 60

